# Generated by Django 3.1.2 on 2020-10-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20201006_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
