# Generated by Django 3.1.2 on 2020-10-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20201008_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Director',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Metascore',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Type',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Writer',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
